
GET http://localhost:6000/api/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGMxZmNiMTZiZWIwZmI2NGU2Y2RiOSIsImlhdCI6MTY0OTIyNjg2MSwiZXhwIjoxNjUxODE4ODYxfQ.ZOmMMuRVMPPUeimINQYGTpH2MDpvYyOmn5XPJghrMvE

###
POST http://localhost:5000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGMxZmNiMTZiZWIwZmI2NGU2Y2RiOSIsImlhdCI6MTY0OTIyNjg2MSwiZXhwIjoxNjUxODE4ODYxfQ.ZOmMMuRVMPPUeimINQYGTpH2MDpvYyOmn5XPJghrMvE

{
    "text":"Lynn add note 11111"
}


###
PUT http://localhost:5000/api/notes/624d34a704844908ee7f1e97
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGMxZmNiMTZiZWIwZmI2NGU2Y2RiOSIsImlhdCI6MTY0OTIyNjg2MSwiZXhwIjoxNjUxODE4ODYxfQ.ZOmMMuRVMPPUeimINQYGTpH2MDpvYyOmn5XPJghrMvE


{
    "text":"Lynn add note 11111 to 2222"
}



###
DELETE http://localhost:5000/api/notes/624d34a704844908ee7f1e97
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGMxZmNiMTZiZWIwZmI2NGU2Y2RiOSIsImlhdCI6MTY0OTIyNjg2MSwiZXhwIjoxNjUxODE4ODYxfQ.ZOmMMuRVMPPUeimINQYGTpH2MDpvYyOmn5XPJghrMvE

