
GET http://localhost:5000/api/notes

###
POST http://localhost:5000/api/notes
Content-Type: application/json




###
PUT http://localhost:5000/api/notes/123

###
DELETE http://localhost:5000/api/notes/123