//注册
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name":"test2",
    "email":"123456@163.com",
    "password":"lynn1234"
}

###
//登录
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email":"1234@163.com",
    "password":"lynn1234"
}

###
//查看用户信息
GET http://localhost:5000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGMxZmNiMTZiZWIwZmI2NGU2Y2RiOSIsImlhdCI6MTY0OTIxMzEwOCwiZXhwIjoxNjUxODA1MTA4fQ.ctqhJT20b07sfux2qT1_zC6UH0c7NZkPKdmnRXlXmMo


